---
title: "Execises"
output: html_document
date: "2024-06-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load, include=FALSE}
library('tidyverse')
```

## R Markdown



```{r }

dat <- read.csv('./Data/femaleMiceWeights.csv')
class(dat)
chowvals <- filter(dat, Diet=='chow') %>% select(Bodyweight)

dat <- read.csv('./Data/msleep_ggplot2.csv')
class(dat)
primates <- dat %>% filter(order == 'Primates')
nrow(primates)
class(primates)
sleep_primates <-  primates %>% select(sleep_total)
class(sleep_primates)

average_sleep <- mean(sleep_primates$sleep_total)
average_sleep <- mean(unlist(sleep_primates))
asleep <- dat %>% 
  filter(order == 'Primates') %>% 
  select(sleep_total) %>% 
  summarise(mean = mean(sleep_total))
```

```{r}
population <- read.csv('./Data/femaleControlsPopulation.csv')
class(population)
population <- unlist(population)
class(population)

for (i in 1:5) {
  control <- sample(population, 12)
  m <- mean(control)
  print(m)
}
```


```{r}
library(UsingR)
x <- father.son$fheight
data(father.son)
str(father.son)
round(sample(x,10), 1)

smallest <- floor( min(x) )
largest <- ceiling( max(x) )
values <- seq(smallest, largest, len=300)
heightecdf <- ecdf(x)

plotdata <- cbind(values, heightecdf(values))
class(plotdata)
plotdata <- data.frame((plotdata
                        ))
plot(values, heightecdf(values), type="l",
     xlab="a (Height in inches)",ylab="Pr(x <= a)")

ggplot(data=plotdata, aes(x=values, y=V2)) +
  geom_line(size = 3)

xdf = data.frame(x)
ggplot(data=xdf, aes(x=x)) +
  geom_histogram(col='red', fill=NA) +
  theme_light()
```


```{r}
population <- read.csv('./Data/femaleControlsPopulation.csv')
mean_overall_weight <- mean(population$Bodyweight)
print(mean_overall_weight)


set.seed(1)
s <- sample(population$Bodyweight, 5)
s_abs_diff = abs(s - mean_overall_weight)
abs(mean_overall_weight - mean(s))

set.seed(5)
s <- sample(population$Bodyweight, 5)
s_abs_diff = abs(s - mean_overall_weight)
abs(mean_overall_weight - mean(s))

set.seed(1)
s <- sample(population$Bodyweight, 5)
s_abs_diff = abs(s - mean_overall_weight)
abs(mean_overall_weight - mean(s))

set.seed(1)

mean_of_samples <- vector('numeric', 1000)
for (i in 1:1000) {
  s <- sample(population$Bodyweight, 5)
  mean_of_sample = mean(s)
  mean_of_samples[i] <- abs(mean_of_sample - mean_overall_weight)
}
bigger <- mean_of_samples > 1
bigger %>% select(bigger == TRUE)

```

